### ISSUE TITLE
Consider turning layers off instead of swallowing keys

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope-TypingBreaks#4]
If we turn layers off instead of swallowing keys, then we can be more lax about the order of using plugins, and TypingBreaks perhaps does not need to be first.

**Comment by algernon** [comment]
Having thought more about this, it would be too complicated: we can't reliably restore the layer state, because of momentary and one-shot layers complicate things a lot. Not to mention that coming back after a 15+ minute break, one may want to start afresh, as far as layers are concerned.

It's better to start swallowing keys instead, as we do now.

**Comment by gedankenexperimenter** [comment]
What about adding an extra layer at the top of the layer stack, full of `XXX` entries? That would (presumably) use more memory, but wouldn't require careful ordering of plugins?

That layer could even be customized by the user so that he could still use the keyboard for other things that (presumably) don't aggravate his hypothetical RSI in the same way as the usual typing.

**Comment by algernon** [comment]
Programmatically expanding the keymap is not currently possible. As in, what you suggest would require the user to manually add that layer to their keymap. While we can make that easy, it won't be as easy as adding the plugin to a list.

Aaand it would use a lot of PROGMEM and/or EEPROM (128 bytes to be precise), and that's too big for a feature that can be implemented another way with reasonable behaviour.
